[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Vite 5 supports Node >= 18; use a modern LTS on Netlify
  NODE_VERSION = "20"

# Single Page App redirect: serve index.html for client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
